DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS deck;
-- DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first VARCHAR(255) NOT NULL,
    last VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE deck (
    id SERIAL PRIMARY KEY,
    deckuser INT REFERENCES users(id) NOT NULL, 
    deckname VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cards (
    id SERIAL PRIMARY KEY,
    decknumber INT REFERENCES deck(id) NOT NULL, 
    front VARCHAR(255) NOT NULL,
    back VARCHAR(255) NOT NULL,
    difficulty VARCHAR(255) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);